### ISSUE TITLE
Add matching alliance tag to corp history

### ISSUE THREAD

**Issue by TheJokr** [TheJokr/vmbot#3]
This would require an API lookup for every of the (up to) 10 coporations to find matching alliance(s).
What happens when there is more than one alliance matching the duration of the corp membership?

**Comment by Hijacker** [comment]
Commas are a quite useful invention

**Comment by TheJokr** [comment]
Will work on this once CCP creates a public Corporation CREST endpoint.

**Comment by TheJokr** [comment]
Closed in favor of XVMX/vmbot#63.
